import Head from 'next/head';
import Quadrant from '../components/Quadrant';
import SideBar from '../components/SideBar';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MingJam&apos;s Diary</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <main className={styles.main}>
        <Quadrant />
      </main>
    </div>
  );
}
